version: '3.8'

services:
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  database:
    container_name: db
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: app
      # You should definitely change the password in production
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - ./db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: on-failure
volumes:
  db:
