version: '3.8'

networks:
  development:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - development
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database
    networks:
      - development
  database:
    container_name: db
    image: postgres:14.3-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-symfony}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_USER: ${POSTGRES_USER:-root}
    volumes:
      - ./db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - development
volumes:
  db:
